import { Alert, Hospital, HospitalReadiness, Match, Organ, Recipient, TimelineEvent, Transport } from '../types/database.types';

export function getInitialHospitals(): Hospital[] {
  return [
    {
      id: 'hosp-mgh-01',
      name: 'Massachusetts General Hospital',
      city: 'Boston',
      state: 'MA',
      country: 'USA',
      latitude: 42.3631,
      longitude: -71.0686,
      contact_phone: '+1 (617) 726-2000',
      or_available: true,
      icu_available: true,
      surgical_team_available: true,
      blood_preparation_ready: true,
      recipient_ready: true,
      readiness_score: 100,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'hosp-bwh-02',
      name: "Brigham and Women's Hospital",
      city: 'Boston',
      state: 'MA',
      country: 'USA',
      latitude: 42.3355,
      longitude: -71.1070,
      contact_phone: '+1 (617) 732-5500',
      or_available: true,
      icu_available: true,
      surgical_team_available: true,
      blood_preparation_ready: false,
      recipient_ready: true,
      readiness_score: 80,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'hosp-nyp-03',
      name: 'NewYork-Presbyterian Columbia',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      latitude: 40.8404,
      longitude: -73.9427,
      contact_phone: '+1 (212) 305-2500',
      or_available: true,
      icu_available: false,
      surgical_team_available: true,
      blood_preparation_ready: true,
      recipient_ready: true,
      readiness_score: 80,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'hosp-msh-04',
      name: 'Mount Sinai Hospital',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      latitude: 40.7900,
      longitude: -73.9526,
      contact_phone: '+1 (212) 241-6500',
      or_available: true,
      icu_available: true,
      surgical_team_available: true,
      blood_preparation_ready: true,
      recipient_ready: false,
      readiness_score: 80,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'hosp-hup-05',
      name: 'Hospital of the University of Pennsylvania',
      city: 'Philadelphia',
      state: 'PA',
      country: 'USA',
      latitude: 39.9500,
      longitude: -75.1936,
      contact_phone: '+1 (215) 662-4000',
      or_available: false,
      icu_available: true,
      surgical_team_available: true,
      blood_preparation_ready: false,
      recipient_ready: true,
      readiness_score: 60,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'hosp-jhh-06',
      name: 'Johns Hopkins Hospital',
      city: 'Baltimore',
      state: 'MD',
      country: 'USA',
      latitude: 39.2965,
      longitude: -76.5927,
      contact_phone: '+1 (410) 955-5000',
      or_available: true,
      icu_available: true,
      surgical_team_available: true,
      blood_preparation_ready: true,
      recipient_ready: true,
      readiness_score: 100,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];
}

export function getInitialOrgans(): Organ[] {
  const now = Date.now();
  return [
    {
      id: 'organ-heart-01',
      organ_type: 'Heart',
      blood_group: 'O+',
      retrieval_time: new Date(now - 105 * 60 * 1000).toISOString(), // retrieved 1h 45m ago
      preservation_start_time: new Date(now - 90 * 60 * 1000).toISOString(), // preservation started 1.5 hrs ago
      maximum_preservation_minutes: 240, // 4 hours max -> remaining ~2.5 hrs
      current_latitude: 41.5000,
      current_longitude: -72.5000,
      status: 'IN_TRANSIT',
      priority: 'CRITICAL_RESCUE',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-lung-02',
      organ_type: 'Lung',
      blood_group: 'O+',
      retrieval_time: new Date(now - 90 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 80 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 360, // 6 hours max
      current_latitude: 42.3450,
      current_longitude: -71.0900,
      status: 'IN_TRANSIT',
      priority: 'URGENT',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-liver-03',
      organ_type: 'Liver',
      blood_group: 'A+',
      retrieval_time: new Date(now - 120 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 110 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 720, // 12 hours max
      current_latitude: 40.5000,
      current_longitude: -74.3000,
      status: 'IN_TRANSIT',
      priority: 'STANDARD',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-kidney-04',
      organ_type: 'Kidney',
      blood_group: 'B+',
      retrieval_time: new Date(now - 240 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 225 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 1440, // 24 hours max
      current_latitude: 39.9500,
      current_longitude: -75.1936,
      status: 'MATCHED',
      priority: 'STANDARD',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-heart-05',
      organ_type: 'Heart',
      blood_group: 'O-',
      retrieval_time: new Date(now - 25 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 20 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 240,
      current_latitude: 39.2965,
      current_longitude: -76.5927,
      status: 'AVAILABLE',
      priority: 'URGENT',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-kidney-06',
      organ_type: 'Kidney',
      blood_group: 'O-',
      retrieval_time: new Date(now - 30 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 25 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 1440,
      current_latitude: 39.2965,
      current_longitude: -76.5927,
      status: 'AVAILABLE',
      priority: 'STANDARD',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-kidney-07',
      organ_type: 'Kidney',
      blood_group: 'A+',
      retrieval_time: new Date(now - 140 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 120 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 1440,
      current_latitude: 40.8404,
      current_longitude: -73.9427,
      status: 'MATCHED',
      priority: 'STANDARD',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'organ-pancreas-08',
      organ_type: 'Pancreas',
      blood_group: 'B+',
      retrieval_time: new Date(now - 180 * 60 * 1000).toISOString(),
      preservation_start_time: new Date(now - 160 * 60 * 1000).toISOString(),
      maximum_preservation_minutes: 720,
      current_latitude: 39.9500,
      current_longitude: -75.1936,
      status: 'AVAILABLE',
      priority: 'STANDARD',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];
}

export function getInitialRecipients(): Recipient[] {
  const now = Date.now();
  return [
    {
      id: 'rec-01',
      recipient_reference: 'REC-NYP-9021',
      organ_type: 'Heart',
      blood_group: 'O+',
      urgency_level: 'CRITICAL',
      waiting_since: new Date(now - 240 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-nyp-03',
      compatibility_data: { hla_match: 5, pra: 8, weight_kg: 72 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-02',
      recipient_reference: 'REC-MSH-4412',
      organ_type: 'Heart',
      blood_group: 'O+',
      urgency_level: 'HIGH',
      waiting_since: new Date(now - 180 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-msh-04',
      compatibility_data: { hla_match: 4, pra: 12, weight_kg: 68 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-03',
      recipient_reference: 'REC-BWH-1049',
      organ_type: 'Lung',
      blood_group: 'O+',
      urgency_level: 'HIGH',
      waiting_since: new Date(now - 95 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-bwh-02',
      compatibility_data: { hla_match: 6, pra: 4, weight_kg: 64 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-04',
      recipient_reference: 'REC-HUP-5521',
      organ_type: 'Liver',
      blood_group: 'A+',
      urgency_level: 'MEDIUM',
      waiting_since: new Date(now - 310 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-hup-05',
      compatibility_data: { hla_match: 4, meld_score: 28 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-05',
      recipient_reference: 'REC-JHH-7782',
      organ_type: 'Kidney',
      blood_group: 'B+',
      urgency_level: 'MEDIUM',
      waiting_since: new Date(now - 620 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-jhh-06',
      compatibility_data: { hla_match: 5, kdpi: 35 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-06',
      recipient_reference: 'REC-MGH-3391',
      organ_type: 'Kidney',
      blood_group: 'O-',
      urgency_level: 'CRITICAL',
      waiting_since: new Date(now - 410 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-mgh-01',
      compatibility_data: { hla_match: 6, pra: 2 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-07',
      recipient_reference: 'REC-BWH-8833',
      organ_type: 'Heart',
      blood_group: 'O-',
      urgency_level: 'CRITICAL',
      waiting_since: new Date(now - 150 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-bwh-02',
      compatibility_data: { hla_match: 5, pra: 5 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-08',
      recipient_reference: 'REC-NYP-6610',
      organ_type: 'Kidney',
      blood_group: 'A+',
      urgency_level: 'LOW',
      waiting_since: new Date(now - 700 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-nyp-03',
      compatibility_data: { hla_match: 4 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-09',
      recipient_reference: 'REC-MSH-9920',
      organ_type: 'Pancreas',
      blood_group: 'B+',
      urgency_level: 'MEDIUM',
      waiting_since: new Date(now - 190 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-msh-04',
      compatibility_data: { hla_match: 5 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
    {
      id: 'rec-10',
      recipient_reference: 'REC-HUP-1200',
      organ_type: 'Lung',
      blood_group: 'O+',
      urgency_level: 'MEDIUM',
      waiting_since: new Date(now - 80 * 24 * 60 * 60 * 1000).toISOString(),
      recipient_hospital_id: 'hosp-hup-05',
      compatibility_data: { hla_match: 3 },
      status: 'WAITING',
      created_at: new Date().toISOString(),
    },
  ];
}

export function getInitialTransports(): Transport[] {
  const now = Date.now();
  return [
    {
      id: 'trans-01',
      organ_id: 'organ-heart-01',
      origin_hospital_id: 'hosp-mgh-01',
      destination_hospital_id: 'hosp-nyp-03',
      transport_mode: 'Helicopter',
      status: 'IN_TRANSIT',
      estimated_distance_km: 315,
      estimated_duration_minutes: 85,
      current_latitude: 41.5000,
      current_longitude: -72.5000,
      eta: new Date(now + 42 * 60 * 1000).toISOString(), // arrival in 42 mins
      delay_minutes: 15,
      route_risk: 'HIGH',
      started_at: new Date(now - 43 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'trans-02',
      organ_id: 'organ-lung-02',
      origin_hospital_id: 'hosp-mgh-01',
      destination_hospital_id: 'hosp-bwh-02',
      transport_mode: 'Ambulance',
      status: 'IN_TRANSIT',
      estimated_distance_km: 8.5,
      estimated_duration_minutes: 25,
      current_latitude: 42.3450,
      current_longitude: -71.0900,
      eta: new Date(now + 12 * 60 * 1000).toISOString(),
      delay_minutes: 0,
      route_risk: 'LOW',
      started_at: new Date(now - 13 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'trans-03',
      organ_id: 'organ-liver-03',
      origin_hospital_id: 'hosp-nyp-03',
      destination_hospital_id: 'hosp-hup-05',
      transport_mode: 'Air Ambulance',
      status: 'IN_TRANSIT',
      estimated_distance_km: 160,
      estimated_duration_minutes: 50,
      current_latitude: 40.5000,
      current_longitude: -74.3000,
      eta: new Date(now + 28 * 60 * 1000).toISOString(),
      delay_minutes: 5,
      route_risk: 'MEDIUM',
      started_at: new Date(now - 22 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'trans-04',
      organ_id: 'organ-kidney-04',
      origin_hospital_id: 'hosp-hup-05',
      destination_hospital_id: 'hosp-jhh-06',
      transport_mode: 'Ambulance',
      status: 'SCHEDULED',
      estimated_distance_km: 155,
      estimated_duration_minutes: 110,
      current_latitude: 39.9500,
      current_longitude: -75.1936,
      eta: new Date(now + 135 * 60 * 1000).toISOString(),
      delay_minutes: 0,
      route_risk: 'LOW',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'trans-05',
      organ_id: 'organ-kidney-07',
      origin_hospital_id: 'hosp-nyp-03',
      destination_hospital_id: 'hosp-msh-04',
      transport_mode: 'Ambulance',
      status: 'SCHEDULED',
      estimated_distance_km: 12,
      estimated_duration_minutes: 30,
      current_latitude: 40.8404,
      current_longitude: -73.9427,
      eta: new Date(now + 45 * 60 * 1000).toISOString(),
      delay_minutes: 0,
      route_risk: 'LOW',
      updated_at: new Date().toISOString(),
    },
  ];
}

export function getInitialHospitalReadiness(): HospitalReadiness[] {
  return [
    {
      id: 'readiness-01',
      hospital_id: 'hosp-nyp-03',
      organ_id: 'organ-heart-01',
      or_ready: true,
      icu_ready: false,
      surgical_team_ready: true,
      blood_ready: true,
      recipient_ready: true,
      readiness_score: 80,
      notes: 'ICU Bed 4 undergoing sterilization; OR team in scrub',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'readiness-02',
      hospital_id: 'hosp-bwh-02',
      organ_id: 'organ-lung-02',
      or_ready: true,
      icu_ready: true,
      surgical_team_ready: true,
      blood_ready: false,
      recipient_ready: true,
      readiness_score: 80,
      notes: 'Cross-matched PRBC arriving from blood bank',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'readiness-03',
      hospital_id: 'hosp-hup-05',
      organ_id: 'organ-liver-03',
      or_ready: false,
      icu_ready: true,
      surgical_team_ready: true,
      blood_ready: false,
      recipient_ready: true,
      readiness_score: 60,
      notes: 'OR 3 turnover delayed by 20 minutes',
      updated_at: new Date().toISOString(),
    },
  ];
}

export function getInitialAlerts(): Alert[] {
  const now = Date.now();
  return [
    {
      id: 'alert-01',
      organ_id: 'organ-heart-01',
      transport_id: 'trans-01',
      hospital_id: 'hosp-nyp-03',
      alert_type: 'SAFETY_MARGIN_LOW',
      severity: 'CRITICAL',
      title: 'Heart Safety Margin Compressed',
      message: 'Helicopter en-route to NYP Columbia delayed by 15 mins. Remaining safety margin is 23 minutes.',
      status: 'ACTIVE',
      created_at: new Date(now - 8 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-02',
      organ_id: 'organ-heart-01',
      hospital_id: 'hosp-nyp-03',
      alert_type: 'HOSPITAL_UNREADY',
      severity: 'HIGH',
      title: 'Receiving ICU Unavailable',
      message: 'NewYork-Presbyterian reports post-op ICU bed not yet sanitized. Readiness stands at 80%.',
      status: 'ACTIVE',
      created_at: new Date(now - 14 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-03',
      organ_id: 'organ-liver-03',
      transport_id: 'trans-03',
      hospital_id: 'hosp-hup-05',
      alert_type: 'READINESS_DELAY',
      severity: 'MEDIUM',
      title: 'OR Turnover Delay at HUP',
      message: 'Operating Room 3 turnover running 20 minutes behind. Surgical team on standby.',
      status: 'ACTIVE',
      created_at: new Date(now - 22 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-04',
      organ_id: 'organ-lung-02',
      transport_id: 'trans-02',
      hospital_id: 'hosp-bwh-02',
      alert_type: 'TRANSIT_PROGRESS',
      severity: 'INFO',
      title: 'Lung Transport On Schedule',
      message: 'Ambulance nearing BWH destination. Estimated arrival in 12 minutes.',
      status: 'ACTIVE',
      created_at: new Date(now - 5 * 60 * 1000).toISOString(),
    },
  ];
}

export function getInitialTimelineEvents(): TimelineEvent[] {
  const now = Date.now();
  return [
    {
      id: 'tl-01',
      organ_id: 'organ-heart-01',
      event_type: 'RETRIEVAL',
      event_time: new Date(now - 105 * 60 * 1000).toISOString(),
      location: 'MGH OR 4, Boston',
      description: 'Cardiac retrieval complete. Cross-clamp time documented.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tl-02',
      organ_id: 'organ-heart-01',
      event_type: 'PRESERVATION_START',
      event_time: new Date(now - 90 * 60 * 1000).toISOString(),
      location: 'MGH Perfusion Lab',
      description: 'Hypothermic machine perfusion initiated. Cold-ischemia clock active.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tl-03',
      organ_id: 'organ-heart-01',
      event_type: 'MATCH_CONFIRMED',
      event_time: new Date(now - 75 * 60 * 1000).toISOString(),
      location: 'Transplant Coordination Center',
      description: 'Candidate REC-NYP-9021 confirmed with 90.5% feasibility match score.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tl-04',
      organ_id: 'organ-heart-01',
      event_type: 'TRANSPORT_DEPARTED',
      event_time: new Date(now - 43 * 60 * 1000).toISOString(),
      location: 'Boston Logan Helipad',
      description: 'MedFlight Helicopter dispatched en route to NYC helipad.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tl-05',
      organ_id: 'organ-heart-01',
      event_type: 'WEATHER_DELAY',
      event_time: new Date(now - 15 * 60 * 1000).toISOString(),
      location: 'Hartford Airspace',
      description: 'Air traffic reroute due to localized headwind adds 15 minutes to ETA.',
      created_at: new Date().toISOString(),
    },
  ];
}

export function getInitialMatches(): Match[] {
  return [
    {
      id: 'match-01',
      organ_id: 'organ-heart-01',
      recipient_id: 'rec-01',
      compatibility_score: 95,
      urgency_score: 98,
      distance_score: 82,
      time_feasibility_score: 80,
      waiting_score: 88,
      overall_score: 90.5,
      status: 'ACCEPTED',
      explanation: {
        summary: 'Top ABO identical match with Tier 1 clinical urgency',
        hla_compatibility: '5/6 antigen match',
      },
      created_at: new Date().toISOString(),
    },
    {
      id: 'match-02',
      organ_id: 'organ-heart-01',
      recipient_id: 'rec-02',
      compatibility_score: 88,
      urgency_score: 85,
      distance_score: 80,
      time_feasibility_score: 82,
      waiting_score: 75,
      overall_score: 83.1,
      status: 'PROPOSED',
      explanation: {
        summary: 'Backup candidate with high urgency and favorable antibody screen',
      },
      created_at: new Date().toISOString(),
    },
    {
      id: 'match-03',
      organ_id: 'organ-lung-02',
      recipient_id: 'rec-03',
      compatibility_score: 98,
      urgency_score: 90,
      distance_score: 99,
      time_feasibility_score: 95,
      waiting_score: 70,
      overall_score: 92.4,
      status: 'ACCEPTED',
      explanation: {
        summary: 'Local recipient within 10km, full antigen match, excellent feasibility',
      },
      created_at: new Date().toISOString(),
    },
  ];
}
